### ISSUE TITLE
Pls help me.i have an issue for configuration not found.anyone that solve this issue??

### ISSUE THREAD

**Issue by GiannisSci** [jwill9999/recipe-app#4]

**Comment by jwill9999** [comment]
I will add a public configuration file this week and update you accordingly

**Comment by Thapelo1** [comment]
Hi Jason,

I hope you don'd mind if I help out the guys out here, because I'm building a similar app and came across your repo, it's actually pretty easy to figure out, since you not using Firstore. 

There's two things you need to get the app working:

1. Create A Firebase project and grab the configuration code and add it to your project. Create a config.ts file and reference that as the config file.

2. Finally Enable the anonymous authorization 

Let me know if it works for yall

Cheers

**Comment by ameshlal** [comment]
Please add a config file for refernce

**Comment by jwill9999** [comment]
Please see readme for details on configuration file and example code. The config file only includes the firebase generated keys generated to access your firebase auth service which you will need to create yourself. This is free.
